# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_remove_images_filtered_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='postId',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='imageRelate', to='posting.Posting'),
        ),
        migrations.AddField(
            model_name='posting',
            name='image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%m/%d/orig'),
        ),
    ]
