# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20170602_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='image',
        ),
    ]
