# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 17:50
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_remove_posting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=smartfields.fields.ImageField(upload_to='image/%Y/%m/%d/orig'),
        ),
    ]
