# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 14:14
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20170609_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=smartfields.fields.ImageField(upload_to='C:\\Users\\sinn5\\Documents\\GitHub\\django-react\\client\\image/%Y/%m/%d/orig'),
        ),
    ]
